spring:
  datasource:
    url: jdbc:postgresql://localhost:5448/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    enabled: true
    drop-first: false
  jpa:
    show-sql: true
  properties:
    hibernate:
      format_sql: true