spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    enabled: true
    drop-first: false
  jpa:
    show-sql: true
  properties:
    hibernate:
      format_sql: true